name: Lint

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  lint:
    name: Run Flake8 Linter
    runs-on: ubuntu-latest

    steps:
      # step 1: check out the repository source code
      - name: Checkout Code
        uses: actions/checkout@v4

      # step 2: use lightweight standard Python for instant linting
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # step 3: install flake8 and flake8 plugins
      - name: Install Flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      # step 4: run Flake8 against source code and test files
      - name: Lint with Flake8
        run: |
          flake8 src tests